{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e6acba2-a533-4718-b520-bfbb46eea4cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total IDs: 500\n",
      "Considering first 500 IDs\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "import os\n",
    "from datetime import datetime, timezone\n",
    "\n",
    "TOP_STORIES_URL = \"https://hacker-news.firebaseio.com/v0/topstories.json\"\n",
    "STORY_URL = \"https://hacker-news.firebaseio.com/v0/item/{}.json\"\n",
    "\n",
    "MAX_STORIES_TO_CHECK = 500\n",
    "MAX_STORIES_PER_CATEGORY = 25\n",
    "\n",
    "# 1. Fetching top story IDs\n",
    "\n",
    "try:\n",
    "    response = requests.get(\n",
    "        TOP_STORIES_URL,\n",
    "        timeout=10\n",
    "    )\n",
    "\n",
    "    response.raise_for_status()\n",
    "\n",
    "    top_story_ids = response.json()\n",
    "\n",
    "except requests.RequestException as error:\n",
    "    print(\"Failed to fetch story IDs:\", error)\n",
    "    top_story_ids = []\n",
    "\n",
    "\n",
    "print(\"Total IDs:\", len(top_story_ids))\n",
    "print(\"Considering first\", MAX_STORIES_TO_CHECK, \"IDs\")\n",
    "\n",
    "\n",
    "# 2. Creating categories\n",
    "\n",
    "categories = {\n",
    "    \"technology\": [],\n",
    "    \"worldnews\": [],\n",
    "    \"sports\": [],\n",
    "    \"science\": [],\n",
    "    \"entertainment\": []\n",
    "}\n",
    "\n",
    "# 3. KeyWords that decide the category of a story title\n",
    "keywords = {\n",
    "    \"technology\": [\"ai\", \"software\", \"computer\", \"programming\", \"code\", \"chip\",\n",
    "                   \"cloud\", \"linux\", \"python\", \"rust\", \"app\", \"data\", \"google\",\n",
    "                   \"apple\", \"microsoft\", \"openai\", \"security\", \"web\", \"tech\"],\n",
    "    \"worldnews\": [\"election\", \"government\", \"war\", \"president\", \"policy\", \"law\",\n",
    "                  \"china\", \"russia\", \"ukraine\", \"india\", \"europe\", \"court\",\n",
    "                  \"tax\", \"ban\", \"police\", \"economy\", \"military\"],\n",
    "    \"sports\": [\"football\", \"cricket\", \"tennis\", \"basketball\", \"baseball\", \"nfl\",\n",
    "               \"nba\", \"olympics\", \"soccer\", \"golf\", \"race\", \"athlete\", \"sport\"],\n",
    "    \"science\": [\"research\", \"nasa\", \"space\", \"physics\", \"biology\", \"climate\",\n",
    "                \"study\", \"scientist\", \"planet\", \"mars\", \"quantum\", \"dna\",\n",
    "                \"brain\", \"energy\", \"math\", \"medicine\"],\n",
    "    \"entertainment\": [\"movie\", \"music\", \"actor\", \"film\", \"tv\", \"game\", \"netflix\",\n",
    "                      \"song\", \"album\", \"show\", \"anime\", \"book\", \"podcast\",\n",
    "                      \"youtube\", \"streaming\"],\n",
    "}\n",
    "\n",
    "# 4. Defining a Function to classify  story titles\n",
    "\n",
    "\n",
    "def find_category(title):\n",
    "    title = title.lower()\n",
    "    for category, words in keywords.items():\n",
    "        for word in words:\n",
    "            if word in title:\n",
    "                return category\n",
    "    return None\n",
    "\n",
    "\n",
    "\n",
    "# 5. Collection timestamp\n",
    "\n",
    "collection_timestamp = datetime.now(\n",
    "    timezone.utc\n",
    ").isoformat()\n",
    "\n",
    "\n",
    "# 6. Fetching and classifying stories\n",
    "\n",
    "for story_id in top_story_ids[:MAX_STORIES_TO_CHECK]:\n",
    "\n",
    "    # Stops when all categories have 25 stories\n",
    "    if all(len(categories[category]) >= MAX_STORIES_PER_CATEGORY\n",
    "        for category in categories):\n",
    "        break\n",
    "\n",
    "    try:\n",
    "\n",
    "        story_response = requests.get(\n",
    "            STORY_URL.format(story_id),\n",
    "            timeout=10\n",
    "        )\n",
    "\n",
    "        story_response.raise_for_status()\n",
    "\n",
    "        story = story_response.json()\n",
    "\n",
    "    except requests.RequestException as error:\n",
    "        print(f\"Failed to fetch story {story_id}: {error}\")\n",
    "        continue\n",
    "\n",
    "\n",
    "    # Making sure the item is a story\n",
    "    \n",
    "    if story.get(\"type\") != \"story\":\n",
    "        continue\n",
    "    title = story.get(\"title\", \"\")\n",
    "    if not title:\n",
    "        continue\n",
    "\n",
    "\n",
    "    # Classify the title\n",
    "    \n",
    "    category = find_category(title)\n",
    "    if category is None:\n",
    "        continue\n",
    "\n",
    "\n",
    "    # Don't collect more than 25 per category\n",
    "    if len(categories[category]) >= MAX_STORIES_PER_CATEGORY:\n",
    "        continue\n",
    "\n",
    "\n",
    "    # Creating the required story record\n",
    "    story_data = {\n",
    "        \"post_id\": story.get(\"id\"),\n",
    "        \"title\": title,\n",
    "        \"category\": category,\n",
    "        \"score\": story.get(\"score\", 0),\n",
    "        \"num_comments\": story.get(\"descendants\", 0),\n",
    "        \"author\": story.get(\"by\", \"\"),\n",
    "        \"collected_at\": collection_timestamp\n",
    "    }\n",
    "\n",
    "\n",
    "    categories[category].append(story_data)\n",
    "\n",
    "# 7. Combining all categories\n",
    "\n",
    "all_stories = []\n",
    "\n",
    "for category in categories:\n",
    "\n",
    "    all_stories.extend(categories[category])\n",
    "\n",
    "# 8. Creating a data folder\n",
    "\n",
    "os.makedirs(\"data\", exist_ok=True)\n",
    "\n",
    "\n",
    "\n",
    "# 9. Creating  dated filename\n",
    "\n",
    "today = datetime.now().strftime(\"%Y%m%d\")\n",
    "\n",
    "filename = f\"data/trends_{today}.json\"\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 10. Save JSON file\n",
    "# --------------------------------------------------\n",
    "\n",
    "with open(filename,\"w\",encoding=\"utf-8\") as file:\n",
    "    json.dump(all_stories,file,indent=2,ensure_ascii=False)\n",
    "\n",
    "print(\"\\nCollection completed!\")\n",
    "print(\"Total stories collected:\", len(all_stories))\n",
    "\n",
    "for category in categories:\n",
    "    print( f\"{category}: {len(categories[category])}\")\n",
    "print(f\"\\nSaved to: {filename}\")\n",
    "\n",
    "\n",
    "# 12. Checking minimum requirement\n",
    "\n",
    "if len(all_stories) >= 100:\n",
    "    print(\"SUCCESS: At least 100 stories collected.\")\n",
    "else:\n",
    "    print(\"WARNING: Less than 100 stories collected.\")\n",
    "    \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ee541bb-2162-46f2-958d-1a4e1b10f42c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
